"""add characters column

Revision ID: 1145e47f4238
Revises: 304b90dd0101
Create Date: 2014-02-17 14:18:36.942001

"""

# revision identifiers, used by Alembic.
revision = '1145e47f4238'
down_revision = '304b90dd0101'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('characters', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'characters')
    ### end Alembic commands ###
