"""add video time columns

Revision ID: 1710dfa54dbd
Revises: 38b5f43b0de2
Create Date: 2013-11-05 11:55:43.367725

"""

# revision identifiers, used by Alembic.
revision = '1710dfa54dbd'
down_revision = '38b5f43b0de2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('race', sa.Column('start_time', sa.Integer(), nullable=True))
    op.add_column('race', sa.Column('video_split', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'video_split')
    op.drop_column('race', 'start_time')
    op.drop_column('race', 'duration')
    ### end Alembic commands ###
