"""add event number

Revision ID: 299a6f2c62b9
Revises: 3084fad1915e
Create Date: 2014-02-09 15:30:42.615554

"""

# revision identifiers, used by Alembic.
revision = '299a6f2c62b9'
down_revision = '3084fad1915e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_number')
    ### end Alembic commands ###

