"""add Tag enum value

Revision ID: 304b90dd0101
Revises: 299a6f2c62b9
Create Date: 2014-02-09 15:31:22.346975

"""

# revision identifiers, used by Alembic.
revision = '304b90dd0101'
down_revision = '299a6f2c62b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('event', 'event_type',
            #type_=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', "Tag", name='event_type'),
            #existing_type=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', name='event_type'))
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('event', 'event_type',
            #existing_type=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', "Tag", name='event_type'),
            #type_=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', name='event_type'))
    pass
    ### end Alembic commands ###

