"""Add region and processed columns

Revision ID: 320e59eac25d
Revises: 5a06ce71a3a6
Create Date: 2014-03-25 14:35:23.452088

"""

# revision identifiers, used by Alembic.
revision = '320e59eac25d'
down_revision = '5a06ce71a3a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('player_regions', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('race', sa.Column('processed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'processed')
    op.drop_column('race', 'player_regions')
    ### end Alembic commands ###
