"""Initial Schema

Revision ID: 364561cdebda
Revises: None
Create Date: 2013-11-04 11:52:11.505887

"""

# revision identifiers, used by Alembic.
revision = '364561cdebda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'session',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('date', sa.DateTime),
        sa.Column('video_url', sa.VARCHAR(100)),
        sa.Column('videl_split', sa.Boolean)
    )
    op.create_table(
        'race',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('session_id', sa.Integer, sa.ForeignKey('session.id')),
        sa.Column('video_url', sa.VARCHAR(100)),
        sa.Column('race_number', sa.Integer)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race')
    op.drop_table('session')
    ### end Alembic commands ###
