"""correct video_split name

Revision ID: 38b5f43b0de2
Revises: 364561cdebda
Create Date: 2013-11-04 15:52:20.844926

"""

# revision identifiers, used by Alembic.
revision = '38b5f43b0de2'
down_revision = '364561cdebda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'videl_split', new_column_name='video_split')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'video_split', new_column_name='videl_split')
    ### end Alembic commands ###
