"""add owner column

Revision ID: 4d73c542db51
Revises: 566b0cc2f2c
Create Date: 2014-04-15 21:29:50.443484

"""

# revision identifiers, used by Alembic.
revision = '4d73c542db51'
down_revision = '566b0cc2f2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('owner', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'owner')
    ### end Alembic commands ###
