"""add fall and reverse

Revision ID: 566b0cc2f2c
Revises: 20c9101ad47f
Create Date: 2014-04-09 21:30:57.061767

"""

# revision identifiers, used by Alembic.
revision = '566b0cc2f2c'
down_revision = '20c9101ad47f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'event_type',
            type_=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', "Tag", 'Reverse', 'Fall', name='event_type'),
            existing_type=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', 'Tag', name='event_type'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'event_type',
            existing_type=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', "Tag", 'Fall', 'Reverse', name='event_type'),
            type_=sa.Enum('Lap', 'Item', 'Collision', 'Pass', 'Shortcut', 'Tag', name='event_type'))
    ### end Alembic commands ###
