"""modify character and course

Revision ID: 5a06ce71a3a6
Revises: 1145e47f4238
Create Date: 2014-02-17 16:39:33.884564

"""

# revision identifiers, used by Alembic.
revision = '5a06ce71a3a6'
down_revision = '1145e47f4238'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('course', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('race', 'characters')
    op.add_column('race', sa.Column('characters', postgresql.ARRAY(sa.VARCHAR(length=16)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'course')
    op.drop_column('race', 'characters')
    op.add_column('race', sa.Column('characters', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###
